# Generated by Django 5.0.14 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectmember_added_by_alter_projectmember_role_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant", "name"], name="projects_pr_tenant__370a12_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant", "created_by"], name="projects_pr_tenant__8194c4_idx"),
        ),
    ]
