# Generated by Django 5.0.14 on 2026-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_tenant__08b9a4_idx',
            old_name='projects_pr_tenant__370a12_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_tenant__12414f_idx',
            old_name='projects_pr_tenant__8194c4_idx',
        ),
    ]
