# Generated by Django 5.0.14 on 2026-02-20 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember_project_completed_at_and_more'),
        ('tasks', '0001_initial'),
        ('tenants', '0003_department_departmentmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='generic', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'recipient', 'read_at', 'created_at'], name='tasks_notif_tenant__d01994_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'assignee', 'status'], name='tasks_task_tenant__b3234d_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='tasks_task_progress_percent_0_100'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['tenant', 'task', 'created_at'], name='tasks_taska_tenant__f69e36_idx'),
        ),
    ]
