# Generated by Django 5.0.14 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskactivity_notification_payload_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["tenant", "due_date"], name="tasks_task_tenant__753d64_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["tenant", "project", "status"], name="tasks_task_tenant__75d857_idx"),
        ),
    ]
