# Generated by Django 5.0.14 on 2026-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_tenant__b3ec32_idx',
            old_name='tasks_task_tenant__753d64_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_tenant__b83bcb_idx',
            old_name='tasks_task_tenant__75d857_idx',
        ),
    ]
