# Generated by Django 5.0.14 on 2026-03-16 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_tasks_task_tenant__753d64_idx_tasks_task_tenant__b3ec32_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
