# Generated by Django 5.0.14 on 2026-02-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_department_departmentmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='subscription_status',
        ),
    ]
