# Generated by Django 5.0.14 on 2026-03-05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import apps.tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_subscriptionplan_workspacesubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceInvite",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(choices=[("owner", "Owner"), ("admin", "Admin"), ("member", "Member")], default="member", max_length=20)),
                ("token", models.CharField(default=apps.tenants.models._default_invite_token, max_length=255, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("invited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspace_invites_sent", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="tenants.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "email"], name="tenants_wor_tenant__54c368_idx"),
                    models.Index(fields=["tenant", "created_at"], name="tenants_wor_tenant__ca32e1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(blank=True, max_length=120)),
                ("signature", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("received", "Received"), ("processed", "Processed"), ("ignored", "Ignored"), ("failed", "Failed")], default="received", max_length=20)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="webhook_events", to="tenants.workspacesubscription")),
                ("workspace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_webhook_events", to="tenants.tenant")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event_type", "status"], name="tenants_bil_event_t_20993f_idx"),
                    models.Index(fields=["workspace", "created_at"], name="tenants_bil_workspa_79f35b_idx"),
                ],
            },
        ),
    ]
