# Generated by Django 5.0.14 on 2026-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_workspaceinvite_billingwebhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingwebhookevent',
            new_name='tenants_bil_event_t_253146_idx',
            old_name='tenants_bil_event_t_20993f_idx',
        ),
        migrations.RenameIndex(
            model_name='billingwebhookevent',
            new_name='tenants_bil_workspa_de8e3b_idx',
            old_name='tenants_bil_workspa_79f35b_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinvite',
            new_name='tenants_wor_tenant__d1dacc_idx',
            old_name='tenants_wor_tenant__54c368_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinvite',
            new_name='tenants_wor_tenant__786098_idx',
            old_name='tenants_wor_tenant__ca32e1_idx',
        ),
    ]
