# Generated by Django 5.0.14 on 2026-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_workspa_1cf24e_idx',
            old_name='audit_audit_workspa_3f53d5_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_workspa_83f834_idx',
            old_name='audit_audit_workspa_f657de_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_workspa_b9b865_idx',
            old_name='audit_audit_workspa_0f03fd_idx',
        ),
    ]
