# Generated by Django 5.0.14 on 2026-03-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_audit_audit_workspa_3f53d5_idx_audit_audit_workspa_1cf24e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_MEMBER_ADDED', 'Project Member Added'), ('PROJECT_MEMBER_REMOVED', 'Project Member Removed'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed')], max_length=64),
        ),
    ]
