# Generated by Django 5.0.14 on 2026-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_workspa_ee6bd3_idx',
            old_name='notificatio_workspa_0ca3f7_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_workspa_a32a5f_idx',
            old_name='notificatio_workspa_d232ab_idx',
        ),
    ]
